AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Name:
    Type: String
    Description: Name of the app

  Project:
    Type: String
    Description: Name of the repo project

  Repository:
    Type: String
    Description: GitHub Repository URL

  Branch:
    Type: String
    Description: Github Repository Branch
    Default: deploy

  OauthToken:
    Type: String
    Description: GitHub Repository URL
    NoEcho: true

  Domain:
    Type: String
    Description: Domain name to host application
    Default: ""

  StaticDomain:
    Type: String
    Description: Static Domain name to host static assets in S3
    Default: "static-sat.smomni.com"

Conditions: 
  UseCustomDomain: !Not [!Equals [!Ref Domain, ""]]

Resources:
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess-Amplify"

  AmplifyApp:
    Type: "AWS::Amplify::App"
    Properties:
      Name: !Ref Name
      Repository: !Ref Repository
      OauthToken: !Ref OauthToken
      IAMServiceRole: !GetAtt AmplifyRole.Arn
      CustomRules: 
        - Source: "/ssr/eventdetail/<*>"
          Status: "301"
          Target: !Join ["", ["https://", !Ref Domain , "/eventdetail/<*>"]]
        - Source: "/login"
          Status: "301"
          Target: !Join ["", ["https://", !Ref Domain , "auth/signin"]]
        - Source: "/gift-registry-images/<*>"
          Status: "200"
          Target: !Join ["", ["https://", !Ref StaticDomain , "/gift-registry-images/<*>"]]
        - Source: "/customer-images/<*>"
          Status: "200"
          Target: !Join ["", ["https://", !Ref StaticDomain , "/customer-images/<*>"]]
        - Source: "/sku-temp-images/<*>"
          Status: "200"
          Target: !Join ["", ["https://", !Ref StaticDomain , "/sku-temp-images/<*>"]]
        - Source: "/gift-wrap-images/<*>"
          Status: "200"
          Target: !Join ["", ["https://", !Ref StaticDomain , "/gift-wrap-images/<*>"]]
        - Source: "/avatar/<*>"
          Status: "200"
          Target: !Join ["", ["https://", !Ref StaticDomain , "/avatar/<*>"]]
        - Source: "/videos/<*>"
          Status: "200"
          Target: !Join ["", ["https://", !Ref StaticDomain , "/videos/<*>"]]
        - Source: "/invoices/<*>"
          Status: "200"
          Target: !Join ["", ["https://", !Ref StaticDomain , "/invoices/<*>"]]
        - Source: "/image-group/<*>"
          Status: "200"
          Target: !Join ["", ["https://", !Ref StaticDomain , "/image-group/<*>"]]
        - Source: "/widget/<*>"
          Status: "200"
          Target: !Join ["", ["https://", !Ref StaticDomain , "/widget/<*>"]]

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: !Ref Branch
      AppId: !GetAtt AmplifyApp.AppId
      EnableAutoBuild: true

  AmplifyDomain:
    Type: AWS::Amplify::Domain
    Condition: UseCustomDomain
    Properties:
      DomainName: !Ref Domain
      AppId: !GetAtt AmplifyApp.AppId
      SubDomainSettings:
        - Prefix: master
          BranchName: !GetAtt AmplifyBranch.BranchName

Outputs:
  DefaultDomain:
    Value: !GetAtt AmplifyApp.DefaultDomain
