name: Deploy Amplify Environment

on:
  workflow_call:
    inputs:
      AWS_REGION: 
        required: false
        type: string
        default: 'ap-southeast-1'
      AMPLIFY_DOMAIN:
        required: false
        type: string
        default: ''
      CORS_PARAM:
        required: false
        type: string
        default: '/applabs/cors/allowedOrigins'
      CORS_HANDLER:
        required: false
        type: string
        default: 'applabs-cors-handler'
    secrets:
      AMPLIFY_TOKEN:
        required: true
      STACK:
        required: true
      ROLE_TO_ASSUME: 
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  amplify:
    name: Deploy to Amplify Console
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
        aws-region:  ${{ inputs.AWS_REGION }}

    - name: Configure environment name
      id: env-name
      env:
        REPO: ${{ github.repository }}
      run: |
        BRANCH=`sed -e 's#.*\/\(\)#\1#' <<< $GITHUB_REF`
        PROJECT=`sed -e 's#.*\/\(\)#\1#' <<< $GITHUB_REPOSITORY`
        ENVIRONMENT=$PROJECT-$BRANCH
        PARAMETER_PREFIX="/$BRANCH/$PROJECT"

        echo "Environment name: $ENVIRONMENT"
        echo "Project name: $PROJECT"
        echo "::set-output name=environment::$ENVIRONMENT"
        echo "::set-output name=project::$PROJECT"
        echo "::set-output name=branch::$BRANCH"
        echo "::set-output name=prameterPrefix::$PARAMETER_PREFIX"

    - name: Deploy to Amplify Console with CloudFormation
      id: amplify-stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ steps.env-name.outputs.environment }}
        template: https://s3.amazonaws.com/smic-applabs-amplify-testing/stack-v2.yml
        no-fail-on-empty-changeset: "1"
        parameter-overrides: >-
          Name=${{ steps.env-name.outputs.environment }},
          Repository=https://github.com/${{ github.repository }},
          Branch=${{ steps.env-name.outputs.branch }},
          OauthToken=${{ secrets.AMPLIFY_TOKEN }},
          Domain=${{ inputs.AMPLIFY_DOMAIN }},
          Project=${{ steps.env-name.outputs.project }}

    - name: Print default domain
      env:
        DefaultDomain: ${{ steps.amplify-stack.outputs.DefaultDomain }}
      run: |
        [[ $DefaultDomain != '' ]] && echo "Default Domain: $DefaultDomain" || echo "Default Domain: None"

    - name: Amplify App Secrets
      env:
        EnvironmentName: ${{ steps.env-name.outputs.environment }}
        PARAM_PREFIX: ${{ steps.env-name.outputs.prameterPrefix }}
        BRANCH: ${{ steps.env-name.outputs.branch }}
        PROJECT: ${{ steps.env-name.outputs.project }}
      run: |
        export AMPLIFY_ID=$(aws amplify list-apps --out json | jq -r '.apps[] | select(.name=="'$EnvironmentName'") | .appId')
        
        if [ $BRANCH == "master" ] 
        then
          PARAM_PREFIX="/production/$PROJECT"
        else
          PARAM_PREFIX="/develop/$PROJECT"
        fi
        
        secrets=$(aws ssm describe-parameters --parameter-filters Key=Name,Option=BeginsWith,Values=$PARAM_PREFIX | jq -r '.Parameters[] | .Name')
        backend_environments=$(aws amplify list-backend-environments --app-id $AMPLIFY_ID | jq -r .backendEnvironments[] | jq -r .environmentName)

        secrets_list=(`echo $secrets | sed 's/" "/\n/g'`)
        backend_environment_list=(`echo $backend_environments | sed 's/" "/\n/g'`)

        for secret in "${secrets_list[@]}"
        do
            secrets_value=$(aws ssm get-parameter --name $secret --with-decryption | jq -r '.Parameter | .Value')
            parameter_name=$(echo $secret | sed -e 's/\/.*\///g')

            for backend in "${backend_environment_list[@]}"
            do  
                echo "/amplify/$AMPLIFY_ID/$backend/$parameter_name"
                aws ssm put-parameter --overwrite --name "/amplify/$AMPLIFY_ID/$backend/$parameter_name" --value "$secrets_value" --type "SecureString"
            done
        done
      shell: bash

    - name: Update CORS
      env:
        DOMAIN: ${{ steps.amplify-stack.outputs.DefaultDomain }}
        CORS_PARAM: ${{ inputs.CORS_PARAM }}
        CORS_HANDLER: ${{ inputs.CORS_HANDLER }}
      run: |
        cors_list=$(aws ssm get-parameter --name $CORS_PARAM | jq -r '.Parameter | .Value')

        [[ $cors_list =~ .*"$DOMAIN".* ]] && exit 0
        
        cors_list+=",$DOMAIN"
        aws ssm put-parameter --name $CORS_PARAM --value $cors_list --type "String" --overwrite
        aws lambda update-function-configuration --function-name $CORS_HANDLER --environment AllowedOrigins=$updated_cors_list
        
        echo $cors_list




    