name: Deploy Amplify Environment

on:
  workflow_call:
    inputs:
      STACK:
        required: true
        type: string
      ROLE_TO_ASSUME: 
        required: true
        type: string
      AWS_REGION: 
        required: false
        type: string
        default: 'ap-southeast-1'
      AMPLIFY_DOMAIN:
        required: false
        type: string
        default: ''
    secrets:
      AMPLIFY_TOKEN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  amplify:
    name: Deploy to Amplify Console
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ inputs.ROLE_TO_ASSUME }}
        aws-region:  ${{ inputs.AWS_REGION }}

    - name: Configure environment name
      id: env-name
      env:
        REPO: ${{ github.repository }}
      run: |
        BRANCH=`sed -e 's#.*\/\(\)#\1#' <<< $GITHUB_REF`
        PROJECT=`sed -e 's#.*\/\(\)#\1#' <<< $GITHUB_REPOSITORY`
        ENVIRONMENT=$PROJECT-$BRANCH
        PARAMETER_PREFIX="/$BRANCH/$PROJECT"
        echo "Environment name: $ENVIRONMENT"
        echo "Project name: $PROJECT"
        echo "::set-output name=environment::$ENVIRONMENT"
        echo "::set-output name=project::$PROJECT"
        echo "::set-output name=branch::$BRANCH"
        echo "::set-output name=prameterPrefix::$PARAMETER_PREFIX"

    - name: Deploy to Amplify Console with CloudFormation
      id: amplify-stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ steps.env-name.outputs.environment }}
        template: ${{ inputs.STACK }}
        no-fail-on-empty-changeset: "1"
        parameter-overrides: >-
          Name=${{ steps.env-name.outputs.environment }},
          Repository=https://github.com/${{ github.repository }},
          Branch=${{ steps.env-name.outputs.branch }},
          OauthToken=${{ secrets.AMPLIFY_TOKEN }},
          Domain=${{ inputs.AMPLIFY_DOMAIN }},
          Project=${{ steps.env-name.outputs.project }}

    - name: Print default domain
      env:
        DefaultDomain: ${{ steps.amplify-stack.outputs.Domain }}
      run: |
        [[ DefaultDomain != '' ]] && echo "Default Domain: $DefaultDomain" || echo "Default Domain: None"

    - name: Amplify App Secrets
      env:
        EnvironmentName: ${{ steps.env-name.outputs.environment }}
        PARAM_PREFIX: ${{ steps.env-name.outputs.prameterPrefix }}
      run: |
        export AMPLIFY_ID=$(aws amplify list-apps --out json | jq -r '.apps[] | select(.name=="'$EnvironmentName'") | .appId')
        ls -la github/workflows/
        ./.github/workflows/scripts/generate-secrets.sh
      shell: bash
    